        !COMPILER-GENERATED INTERFACE MODULE: Tue Apr 30 11:21:56 2024
        MODULE CALC__genmod
          INTERFACE 
            SUBROUTINE CALC
            END SUBROUTINE CALC
          END INTERFACE 
        END MODULE CALC__genmod
