        !COMPILER-GENERATED INTERFACE MODULE: Thu May 16 23:39:32 2024
        MODULE CALCULATION__genmod
          INTERFACE 
            SUBROUTINE CALCULATION
            END SUBROUTINE CALCULATION
          END INTERFACE 
        END MODULE CALCULATION__genmod
