        !COMPILER-GENERATED INTERFACE MODULE: Thu May 16 23:26:51 2024
        MODULE LESSON1__genmod
          INTERFACE 
            SUBROUTINE LESSON1
            END SUBROUTINE LESSON1
          END INTERFACE 
        END MODULE LESSON1__genmod
