        !COMPILER-GENERATED INTERFACE MODULE: Fri May 17 08:50:16 2024
        MODULE LESSON4__genmod
          INTERFACE 
            SUBROUTINE LESSON4
            END SUBROUTINE LESSON4
          END INTERFACE 
        END MODULE LESSON4__genmod
