        !COMPILER-GENERATED INTERFACE MODULE: Thu May 16 20:46:26 2024
        MODULE LESSON2__genmod
          INTERFACE 
            SUBROUTINE LESSON2
            END SUBROUTINE LESSON2
          END INTERFACE 
        END MODULE LESSON2__genmod
