        !COMPILER-GENERATED INTERFACE MODULE: Thu May 16 23:42:04 2024
        MODULE LESSON3__genmod
          INTERFACE 
            SUBROUTINE LESSON3
            END SUBROUTINE LESSON3
          END INTERFACE 
        END MODULE LESSON3__genmod
