        !COMPILER-GENERATED INTERFACE MODULE: Tue Apr 30 14:07:21 2024
        MODULE CALCULATION__genmod
          INTERFACE 
            SUBROUTINE CALCULATION
            END SUBROUTINE CALCULATION
          END INTERFACE 
        END MODULE CALCULATION__genmod
